# Generated by Django 4.0.5 on 2022-07-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название ингредиента.', max_length=250, verbose_name='Название ингредиента')),
                ('unit', models.CharField(choices=[('кг', 'Килограмм'), ('г', 'грамм'), ('л', 'литров'), ('мл', 'милилитров')], help_text='Введите единицы измерения().', max_length=2, verbose_name='Единицы измерения')),
            ],
            options={
                'verbose_name': 'Ингредиент',
                'verbose_name_plural': 'Ингредиенты',
                'ordering': ['name'],
            },
        ),
    ]
