# Generated by Django 4.0.5 on 2022-07-11 18:10

from django.db import migrations
import django_base64field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=255, null=True, verbose_name='Картинка'),
        ),
    ]
