# Generated by Django 4.0.5 on 2022-07-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, help_text='Можете добавить фото.', max_length=10000000, upload_to='recipes/images/', verbose_name='Картинка'),
        ),
    ]
